name: nowbar

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ^3.12.2


dependencies:

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8


  # ウィンドウ制御
  window_manager: ^0.5.2


  # ウィンドウドラッグ・サイズ制御
  bitsdojo_window: ^0.1.6


  # その他
  http: ^1.2.2
  url_launcher: ^6.3.2



dev_dependencies:

  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0



flutter:

  uses-material-design: true